/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      // Mobile-first breakpoints
      'mobile': {'max': '640px'},
      'tablet': {'min': '641px', 'max': '1024px'},
      'desktop': {'min': '1025px'},
      // Orientation and device specific
      'portrait': {'raw': '(orientation: portrait)'},
      'landscape': {'raw': '(orientation: landscape)'},
      'touch': {'raw': '(pointer: coarse)'},
      'mouse': {'raw': '(pointer: fine)'},
      'retina': {'raw': '(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)'},
    },
    extend: {
      colors: {
        // Theme-aware colors using CSS custom properties
        'theme-primary': {
          50: 'rgb(var(--theme-primary-50) / <alpha-value>)',
          100: 'rgb(var(--theme-primary-100) / <alpha-value>)',
          200: 'rgb(var(--theme-primary-200) / <alpha-value>)',
          300: 'rgb(var(--theme-primary-300) / <alpha-value>)',
          400: 'rgb(var(--theme-primary-400) / <alpha-value>)',
          500: 'rgb(var(--theme-primary-500) / <alpha-value>)',
          600: 'rgb(var(--theme-primary-600) / <alpha-value>)',
          700: 'rgb(var(--theme-primary-700) / <alpha-value>)',
          800: 'rgb(var(--theme-primary-800) / <alpha-value>)',
          900: 'rgb(var(--theme-primary-900) / <alpha-value>)',
          950: 'rgb(var(--theme-primary-950) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-primary) / <alpha-value>)',
        },
        'theme-secondary': {
          50: 'rgb(var(--theme-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--theme-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--theme-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--theme-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--theme-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--theme-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--theme-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--theme-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--theme-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--theme-secondary-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-secondary) / <alpha-value>)',
        },
        'theme-accent': {
          50: 'rgb(var(--theme-accent-50) / <alpha-value>)',
          100: 'rgb(var(--theme-accent-100) / <alpha-value>)',
          200: 'rgb(var(--theme-accent-200) / <alpha-value>)',
          300: 'rgb(var(--theme-accent-300) / <alpha-value>)',
          400: 'rgb(var(--theme-accent-400) / <alpha-value>)',
          500: 'rgb(var(--theme-accent-500) / <alpha-value>)',
          600: 'rgb(var(--theme-accent-600) / <alpha-value>)',
          700: 'rgb(var(--theme-accent-700) / <alpha-value>)',
          800: 'rgb(var(--theme-accent-800) / <alpha-value>)',
          900: 'rgb(var(--theme-accent-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-accent) / <alpha-value>)',
        },
        'theme-success': {
          50: 'rgb(var(--theme-success-50) / <alpha-value>)',
          100: 'rgb(var(--theme-success-100) / <alpha-value>)',
          200: 'rgb(var(--theme-success-200) / <alpha-value>)',
          300: 'rgb(var(--theme-success-300) / <alpha-value>)',
          400: 'rgb(var(--theme-success-400) / <alpha-value>)',
          500: 'rgb(var(--theme-success-500) / <alpha-value>)',
          600: 'rgb(var(--theme-success-600) / <alpha-value>)',
          700: 'rgb(var(--theme-success-700) / <alpha-value>)',
          800: 'rgb(var(--theme-success-800) / <alpha-value>)',
          900: 'rgb(var(--theme-success-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-success) / <alpha-value>)',
        },
        'theme-warning': {
          50: 'rgb(var(--theme-warning-50) / <alpha-value>)',
          100: 'rgb(var(--theme-warning-100) / <alpha-value>)',
          200: 'rgb(var(--theme-warning-200) / <alpha-value>)',
          300: 'rgb(var(--theme-warning-300) / <alpha-value>)',
          400: 'rgb(var(--theme-warning-400) / <alpha-value>)',
          500: 'rgb(var(--theme-warning-500) / <alpha-value>)',
          600: 'rgb(var(--theme-warning-600) / <alpha-value>)',
          700: 'rgb(var(--theme-warning-700) / <alpha-value>)',
          800: 'rgb(var(--theme-warning-800) / <alpha-value>)',
          900: 'rgb(var(--theme-warning-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-warning) / <alpha-value>)',
        },
        'theme-error': {
          50: 'rgb(var(--theme-error-50) / <alpha-value>)',
          100: 'rgb(var(--theme-error-100) / <alpha-value>)',
          200: 'rgb(var(--theme-error-200) / <alpha-value>)',
          300: 'rgb(var(--theme-error-300) / <alpha-value>)',
          400: 'rgb(var(--theme-error-400) / <alpha-value>)',
          500: 'rgb(var(--theme-error-500) / <alpha-value>)',
          600: 'rgb(var(--theme-error-600) / <alpha-value>)',
          700: 'rgb(var(--theme-error-700) / <alpha-value>)',
          800: 'rgb(var(--theme-error-800) / <alpha-value>)',
          900: 'rgb(var(--theme-error-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-error) / <alpha-value>)',
        },
        'theme-background': {
          50: 'rgb(var(--theme-bg-50) / <alpha-value>)',
          100: 'rgb(var(--theme-bg-100) / <alpha-value>)',
          200: 'rgb(var(--theme-bg-200) / <alpha-value>)',
          300: 'rgb(var(--theme-bg-300) / <alpha-value>)',
          400: 'rgb(var(--theme-bg-400) / <alpha-value>)',
          500: 'rgb(var(--theme-bg-500) / <alpha-value>)',
          600: 'rgb(var(--theme-bg-600) / <alpha-value>)',
          700: 'rgb(var(--theme-bg-700) / <alpha-value>)',
          800: 'rgb(var(--theme-bg-800) / <alpha-value>)',
          900: 'rgb(var(--theme-bg-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-background) / <alpha-value>)',
        },
        'theme-surface': {
          50: 'rgb(var(--theme-surface-50) / <alpha-value>)',
          100: 'rgb(var(--theme-surface-100) / <alpha-value>)',
          200: 'rgb(var(--theme-surface-200) / <alpha-value>)',
          300: 'rgb(var(--theme-surface-300) / <alpha-value>)',
          400: 'rgb(var(--theme-surface-400) / <alpha-value>)',
          500: 'rgb(var(--theme-surface-500) / <alpha-value>)',
          600: 'rgb(var(--theme-surface-600) / <alpha-value>)',
          700: 'rgb(var(--theme-surface-700) / <alpha-value>)',
          800: 'rgb(var(--theme-surface-800) / <alpha-value>)',
          900: 'rgb(var(--theme-surface-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-surface) / <alpha-value>)',
        },
        'theme-text': {
          50: 'rgb(var(--theme-text-50) / <alpha-value>)',
          100: 'rgb(var(--theme-text-100) / <alpha-value>)',
          200: 'rgb(var(--theme-text-200) / <alpha-value>)',
          300: 'rgb(var(--theme-text-300) / <alpha-value>)',
          400: 'rgb(var(--theme-text-400) / <alpha-value>)',
          500: 'rgb(var(--theme-text-500) / <alpha-value>)',
          600: 'rgb(var(--theme-text-600) / <alpha-value>)',
          700: 'rgb(var(--theme-text-700) / <alpha-value>)',
          800: 'rgb(var(--theme-text-800) / <alpha-value>)',
          900: 'rgb(var(--theme-text-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-text) / <alpha-value>)',
        },
        'theme-border': {
          50: 'rgb(var(--theme-border-50) / <alpha-value>)',
          100: 'rgb(var(--theme-border-100) / <alpha-value>)',
          200: 'rgb(var(--theme-border-200) / <alpha-value>)',
          300: 'rgb(var(--theme-border-300) / <alpha-value>)',
          400: 'rgb(var(--theme-border-400) / <alpha-value>)',
          500: 'rgb(var(--theme-border-500) / <alpha-value>)',
          600: 'rgb(var(--theme-border-600) / <alpha-value>)',
          700: 'rgb(var(--theme-border-700) / <alpha-value>)',
          800: 'rgb(var(--theme-border-800) / <alpha-value>)',
          900: 'rgb(var(--theme-border-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--theme-border) / <alpha-value>)',
        },
        // Legacy static colors for backward compatibility
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0369a1',
          700: '#075985',
          800: '#0c4a6e',
          900: '#082f49',
          950: '#041e2d',
        },
        secondary: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
        accent: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        danger: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        dark: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
          950: '#030712',
        }
      },
      fontFamily: {
        'alarm': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'system-ui', 'sans-serif'],
        'display': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Consolas', 'Monaco', 'monospace'],
        // Theme-aware fonts
        'theme': 'var(--theme-font-family)',
        'theme-display': 'var(--theme-font-family-display)',
        'theme-mono': 'var(--theme-font-family-mono)',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.75rem' }],
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        // Theme-aware font sizes
        'theme-2xs': 'calc(var(--theme-font-size-base) * 0.625)',
        'theme-xs': 'calc(var(--theme-font-size-base) * 0.75)',
        'theme-sm': 'calc(var(--theme-font-size-base) * 0.875)',
        'theme-base': 'var(--theme-font-size-base)',
        'theme-lg': 'calc(var(--theme-font-size-base) * 1.125)',
        'theme-xl': 'calc(var(--theme-font-size-base) * 1.25)',
        'theme-2xl': 'calc(var(--theme-font-size-base) * 1.5)',
        'theme-3xl': 'calc(var(--theme-font-size-base) * 1.875)',
        'theme-4xl': 'calc(var(--theme-font-size-base) * 2.25)',
        'theme-5xl': 'calc(var(--theme-font-size-base) * 3)',
        'theme-6xl': 'calc(var(--theme-font-size-base) * 3.75)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        // Mobile-optimized spacing
        'mobile-xs': '0.25rem',
        'mobile-sm': '0.5rem',
        'mobile-md': '1rem',
        'mobile-lg': '1.5rem',
        'mobile-xl': '2rem',
        // Touch-friendly sizes
        'touch-sm': '2.75rem', // 44px min touch target
        'touch-md': '3.5rem',  // 56px recommended
        'touch-lg': '4rem',    // 64px comfortable
        // Theme-aware spacing
        'theme-xs': 'var(--theme-spacing-xs)',
        'theme-sm': 'var(--theme-spacing-sm)',
        'theme-md': 'var(--theme-spacing-md)',
        'theme-lg': 'var(--theme-spacing-lg)',
        'theme-xl': 'var(--theme-spacing-xl)',
        'theme-2xl': 'var(--theme-spacing-2xl)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        // Theme-aware border radius
        'theme-none': 'var(--theme-radius-none)',
        'theme-sm': 'var(--theme-radius-sm)',
        'theme': 'var(--theme-radius-md)',
        'theme-md': 'var(--theme-radius-md)',
        'theme-lg': 'var(--theme-radius-lg)',
        'theme-xl': 'var(--theme-radius-xl)',
        'theme-2xl': 'var(--theme-radius-2xl)',
        'theme-full': 'var(--theme-radius-full)',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'glow': '0 0 20px rgba(59, 130, 246, 0.3)',
        'alarm': '0 0 30px rgba(239, 68, 68, 0.4)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        // Theme-aware shadows
        'theme-sm': 'var(--theme-shadow-sm)',
        'theme': 'var(--theme-shadow-md)',
        'theme-md': 'var(--theme-shadow-md)',
        'theme-lg': 'var(--theme-shadow-lg)',
        'theme-xl': 'var(--theme-shadow-xl)',
        'theme-2xl': 'var(--theme-shadow-2xl)',
        'theme-inner': 'var(--theme-shadow-inner)',
      },
      backdropBlur: {
        'xs': '2px',
        '4xl': '72px',
      },
      animation: {
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite',
        'alarm-shake': 'alarm-shake 0.5s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'slide-up': 'slide-up 0.3s ease-out',
        'slide-down': 'slide-down 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite alternate',
        'bounce-subtle': 'bounce-subtle 1s ease-in-out infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
      },
      keyframes: {
        'pulse-ring': {
          '0%': { transform: 'scale(0.33)', opacity: '1' },
          '80%, 100%': { transform: 'scale(2.33)', opacity: '0' },
        },
        'alarm-shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(4px)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'glow-pulse': {
          '0%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.3)' },
          '100%': { boxShadow: '0 0 40px rgba(59, 130, 246, 0.6)' },
        },
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        'wiggle': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-2deg)' },
          '75%': { transform: 'rotate(2deg)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'glass-gradient': 'linear-gradient(135deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.05) 100%)',
        'aurora': 'linear-gradient(45deg, #6366f1, #8b5cf6, #ec4899, #f59e0b)',
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.glass': {
          'background': 'rgba(255, 255, 255, 0.1)',
          'backdrop-filter': 'blur(10px)',
          'border': '1px solid rgba(255, 255, 255, 0.2)',
        },
        '.glass-dark': {
          'background': 'rgba(0, 0, 0, 0.2)',
          'backdrop-filter': 'blur(10px)',
          'border': '1px solid rgba(255, 255, 255, 0.1)',
        },
        '.gradient-text': {
          'background': 'linear-gradient(45deg, #6366f1, #8b5cf6)',
          '-webkit-background-clip': 'text',
          'background-clip': 'text',
          '-webkit-text-fill-color': 'transparent',
        },
        // Theme-aware utilities
        '.theme-glass': {
          'background': 'var(--theme-glass-background)',
          'backdrop-filter': 'var(--theme-glass-blur)',
          'border': '1px solid var(--theme-glass-border)',
        },
        '.theme-gradient-text': {
          'background': 'var(--theme-gradient-primary)',
          '-webkit-background-clip': 'text',
          'background-clip': 'text',
          '-webkit-text-fill-color': 'transparent',
        },
        '.theme-card': {
          'background-color': 'var(--theme-surface)',
          'border': '1px solid var(--theme-border)',
          'border-radius': 'var(--theme-radius-md)',
          'box-shadow': 'var(--theme-shadow-sm)',
        },
        '.theme-button': {
          'background-color': 'var(--theme-primary)',
          'color': 'var(--theme-text-on-primary)',
          'border-radius': 'var(--theme-radius-md)',
          'padding': 'var(--theme-spacing-sm) var(--theme-spacing-md)',
          'font-weight': '500',
          'transition': 'all var(--theme-transition-fast)',
        },
        '.theme-button-secondary': {
          'background-color': 'var(--theme-surface)',
          'color': 'var(--theme-text)',
          'border': '1px solid var(--theme-border)',
          'border-radius': 'var(--theme-radius-md)',
          'padding': 'var(--theme-spacing-sm) var(--theme-spacing-md)',
          'font-weight': '500',
          'transition': 'all var(--theme-transition-fast)',
        },
        '.reduce-motion': {
          'transition': 'none !important',
          'animation': 'none !important',
        },
        // Mobile-specific utilities
        '.mobile-touch': {
          'min-height': '44px',
          'min-width': '44px',
          'touch-action': 'manipulation',
        },
        '.mobile-input': {
          'font-size': '16px', // Prevent zoom on iOS
          'min-height': '44px',
        },
        '.mobile-safe-top': {
          'padding-top': 'env(safe-area-inset-top)',
        },
        '.mobile-safe-bottom': {
          'padding-bottom': 'env(safe-area-inset-bottom)',
        },
        '.mobile-safe-left': {
          'padding-left': 'env(safe-area-inset-left)',
        },
        '.mobile-safe-right': {
          'padding-right': 'env(safe-area-inset-right)',
        },
        '.mobile-scroll': {
          'overflow-y': 'auto',
          '-webkit-overflow-scrolling': 'touch',
          'overscroll-behavior-y': 'contain',
        },
        '.mobile-tap-highlight': {
          '-webkit-tap-highlight-color': 'transparent',
        },
      }
      addUtilities(newUtilities)
    }
  ],
  darkMode: ['class', '[data-theme="dark"]'],
}