// TODO: verify removal - This component appears to be unused/dead code
// Generated by dead code cleanup script
// Original content commented out:

// /// <reference lib="dom" />
// // Comprehensive Security Dashboard Component
// // Provides a unified interface for monitoring all alarm security features
// // Styled to match the Relife app's design system with glassmorphism and modern effects
//
// import React, { useState, useEffect } from 'react';
// import {
//   Shield,
//   Alert,
//   CheckCircle,
//   XCircle,
//   RefreshCw,
//   Archive,
//   Eye,
//   Zap,
//   Lock,
//   Activity,
//   ShieldCheck,
// } from 'lucide-react';
// import AlarmSecurityIntegrationService from '../services/alarm-security-integration';
// import SecurityMonitoringForensicsService from '../services/security-monitoring-forensics';
// import _AlarmBackupRedundancyService from '../services/alarm-backup-redundancy';
// import _AlarmRateLimitingService from '../services/alarm-rate-limiting';
// import { TimeoutHandle } from '../types/timers';
//
// interface SecurityStatus {
//   overall: 'secure' | 'warning' | 'critical' | 'compromised';
//   components: {
//     storage: 'active' | 'degraded' | 'failed';
//     integrity: 'monitoring' | 'degraded' | 'compromised';
//     pushSecurity: 'active' | 'degraded' | 'failed';
//     accessControl: 'active' | 'bypassed' | 'failed';
//     backup: 'healthy' | 'degraded' | 'failed';
//     monitoring: 'active' | 'degraded' | 'offline';
//     rateLimiting: 'active' | 'degraded' | 'bypassed';
//     apiSecurity: 'active' | 'degraded' | 'failed';
//   };
//   metrics: {
//     totalThreats: number;
//     activeAlerts: number;
//     backupHealth: number;
//     integrityScore: number;
//     lastUpdate: Date;
//   };
//   recommendations: string[];
// }
//
// interface SecurityAlert {
//   id: string;
//   timestamp: Date;
//   type: 'immediate' | 'hourly' | 'daily';
//   severity: 'low' | 'medium' | 'high' | 'critical';
//   title: string;
//   description: string;
//   acknowledged: boolean;
//   resolved: boolean;
// }
//
// // TODO: verify removal - ComprehensiveSecurityDashboard component appears to be unused
// // const ComprehensiveSecurityDashboard: React.FC = (
// // ) => {
// //   const [securityStatus, setSecurityStatus] = useState<SecurityStatus | null>(null);
// //   const [activeAlerts, setActiveAlerts] = useState<SecurityAlert[]>([]);
// //   const [diagnosticsResults, setDiagnosticsResults] = useState<any>(null);
// //   const [loading, setLoading] = useState(true);
// //   const [selectedTab, setSelectedTab] = useState<
// //     'overview' | 'alerts' | 'diagnostics' | 'backup'
// //   >('overview');
// //   const [autoRefresh, setAutoRefresh] = useState(true);
// //
// //   useEffect((
// // ) => {
// //     loadSecurityData();
// //
// //     if (autoRefresh) {
// //       const interval = setInterval(loadSecurityData, 30000); // Refresh every 30 seconds
// //       return (
// // ) => clearInterval(interval);
// //     }
// //   }, [autoRefresh]);
// //
// //   useEffect((
// // ) => {
// //     // Listen for real-time security events
// //     const handleSecurityAlert = (event: any
// // ) => {
// //       console.log('New security alert:', event.detail);
// //       loadSecurityData(); // Refresh data when new alerts come in
// //     };
// //
// //     const handleTamperDetection = (event: any
// // ) => {
// //       console.error('Tamper detection:', event.detail);
// //       loadSecurityData();
// //     };
// //
// //     window.addEventListener('security-alert-created', handleSecurityAlert);
// //     window.addEventListener('alarm-tamper-detected', handleTamperDetection);
// //
// //     return (
// // ) => {
// //       window.removeEventListener('security-alert-created', handleSecurityAlert);
// //       window.removeEventListener('alarm-tamper-detected', handleTamperDetection);
// //     };
// //   }, []);
// //
// //   const loadSecurityData = async (
// // ) => {
// //     try {
// //       setLoading(true);
// //
// //       // Load security status
// //       const status = await AlarmSecurityIntegrationService.getSecurityStatus();
// //       setSecurityStatus(status);
// //
// //       // Load active alerts
// //       const alerts = await SecurityMonitoringForensicsService.getActiveAlerts();
// //       setActiveAlerts(alerts);
// //     } catch (error) {
// //       console.error('Failed to load security data:', error);
// //     } finally {
// //       setLoading(false);
// //     }
// //   };
// //
// //   const runDiagnostics = async (
// // ) => {
// //     try {
// //       setLoading(true);
// //       const results = await AlarmSecurityIntegrationService.runSecurityDiagnostics();
// //       setDiagnosticsResults(results);
// //     } catch (error) {
// //       console.error('Failed to run diagnostics:', error);
// //     } finally {
// //       setLoading(false);
// //     }
// //   };
// //
// //   const acknowledgeAlert = async (alertId: string
// // ) => {
// //     try {
// //       await SecurityMonitoringForensicsService.acknowledgeAlert(alertId);
// //       await loadSecurityData();
// //     } catch (error) {
// //       console.error('Failed to acknowledge alert:', error);
// //     }
// //   };
// //
// //   const resolveAlert = async (alertId: string
// // ) => {
// //     try {
// //       await SecurityMonitoringForensicsService.resolveAlert(alertId);
// //       await loadSecurityData();
// //     } catch (error) {
// //       console.error('Failed to resolve alert:', error);
// //     }
// //   };
// //
// //   const getStatusColor = (status: string
// // ) => {
// //     switch (status) {
// //       case 'secure':
// //       case 'active':
// //       case 'healthy':
// //       case 'monitoring':
// //         return 'text-green-700 dark:text-green-300 bg-green-100/80 dark:bg-green-900/40 border border-green-200/50 dark:border-green-700/30';
// //       case 'warning':
// //       case 'degraded':
// //         return 'text-yellow-700 dark:text-yellow-300 bg-yellow-100/80 dark:bg-yellow-900/40 border border-yellow-200/50 dark:border-yellow-700/30';
// //       case 'critical':
// //       case 'failed':
// //       case 'compromised':
// //       case 'offline':
// //       case 'bypassed':
// //         return 'text-red-700 dark:text-red-300 bg-red-100/80 dark:bg-red-900/40 border border-red-200/50 dark:border-red-700/30';
// //       default:
// //         return 'text-gray-700 dark:text-gray-300 bg-gray-100/80 dark:bg-gray-800/40 border border-gray-200/50 dark:border-gray-700/30';
// //     }
// //   };
// //
// //   const getStatusIcon = (status: string
// // ) => {
// //     switch (status) {
// //       case 'secure':
// //       case 'active':
// //       case 'healthy':
// //       case 'monitoring':
// //       case 'passed':
// //         return (
// //           <CheckCircle
// //             className="w-5 h-5 text-green-600 dark:text-green-400"
// //             aria-hidden="true"
// //           />
// //         );
// //       case 'warning':
// //       case 'degraded':
// //         return (
// //           <Alert
// //             className="w-5 h-5 text-yellow-600 dark:text-yellow-400"
// //             aria-hidden="true"
// //           />
// //         );
// //       case 'critical':
// //       case 'failed':
// //       case 'compromised':
// //       case 'offline':
// //       case 'bypassed':
// //         return (
// //           <XCircle
// //             className="w-5 h-5 text-red-600 dark:text-red-400"
// //             aria-hidden="true"
// //           />
// //         );
// //       default:
// //         return (
// //           <RefreshCw
// //             className="w-5 h-5 text-gray-600 dark:text-gray-400"
// //             aria-hidden="true"
// //           />
// //         );
// //     }
// //   };
// //
// //   const getSeverityColor = (severity: string
// // ) => {
// //     switch (severity) {
// //       case 'low':
// //         return 'text-primary-700 dark:text-primary-300 bg-primary-100/80 dark:bg-primary-900/40 border border-primary-200/50 dark:border-primary-700/30';
// //       case 'medium':
// //         return 'text-yellow-700 dark:text-yellow-300 bg-yellow-100/80 dark:bg-yellow-900/40 border border-yellow-200/50 dark:border-yellow-700/30';
// //       case 'high':
// //         return 'text-orange-700 dark:text-orange-300 bg-orange-100/80 dark:bg-orange-900/40 border border-orange-200/50 dark:border-orange-700/30';
// //       case 'critical':
// //         return 'text-red-700 dark:text-red-300 bg-red-100/80 dark:bg-red-900/40 border border-red-200/50 dark:border-red-700/30';
// //       default:
// //         return 'text-gray-700 dark:text-gray-300 bg-gray-100/80 dark:bg-gray-800/40 border border-gray-200/50 dark:border-gray-700/30';
// //     }
// //   };
// //
// //   if (loading && !securityStatus) {
// //     return (
// //       <div className="flex items-center justify-center p-8 min-h-screen">
// //         <div className="text-center">
// //           <RefreshCw className="w-12 h-12 animate-spin text-primary-500 mx-auto mb-4" />
// //           <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
// //             Loading Security Dashboard
// //           </h2>
// //           <p className="text-gray-600 dark:text-gray-400">
// //             Initializing security monitoring systems...
// //           </p>
// //         </div>
// //       </div>
// //     );
// //   }
// //
// //   return (
// //     <main
// //       className="min-h-screen bg-gray-50 dark:bg-dark-900"
// //       role="main"
// //       aria-labelledby="security-dashboard-heading"
// //     >
// //       <div className="max-w-6xl mx-auto p-4 space-y-6">
// //         {/* Header */}
// //         <section
// //           className="alarm-card bg-gradient-to-br from-primary-500 to-primary-700 text-white"
// //           role="region"
// //           aria-labelledby="security-header"
// //         >
// //           <div className="flex items-center justify-between">
// //             <div className="flex items-center space-x-3">
// //               <div className="p-3 rounded-full bg-white/20 backdrop-blur-sm">
// //                 <Shield className="w-8 h-8" aria-hidden="true" />
// //               </div>
// //               <div>
// //                 <h1 id="security-dashboard-heading" className="text-3xl font-bold">
// //                   Security Dashboard
// //                 </h1>
// //                 <p className="text-white/90 text-sm">
// //                   Monitor and manage alarm security systems
// //                 </p>
// //               </div>
// //             </div>
// //
// //             <div className="flex items-center space-x-4">
// //               <label className="flex items-center space-x-2 glass-card px-3 py-2 rounded-lg">
// //                 <input
// //                   type="checkbox"
// //                   checked={autoRefresh}
// //
// //                   onChange={(e: any
// // ) => setAutoRefresh(e.target.checked)}
// //                   className="alarm-toggle rounded border-white/30 text-primary-500 focus:ring-primary-300 bg-white/10"
// //                   aria-describedby="auto-refresh-desc"
// //                 />
// //                 <span id="auto-refresh-desc" className="text-sm text-white/90">
// //                   Auto-refresh
// //                 </span>
// //               </label>
// //
// //               <button
// //                 onClick={loadSecurityData}
// //                 disabled={loading}
// //                 className="alarm-button alarm-button-secondary flex items-center space-x-2 px-4 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg backdrop-blur-sm transition-all disabled:opacity-50"
// //                 aria-label="Refresh security data"
// //               >
// //                 <RefreshCw
// //                   className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`}
// //                   aria-hidden="true"
// //                 />
// //                 <span>Refresh</span>
// //               </button>
// //             </div>
// //           </div>
// //         </section>
// //
// //         {/* Overall Status Card */}
// //         {securityStatus && (
// //           <section
// //             className={`alarm-card glass-card border-2 ${
// //               securityStatus.overall === 'secure'
// //                 ? 'border-green-300/50 bg-gradient-to-br from-green-50/80 to-emerald-50/80 dark:from-green-900/20 dark:to-emerald-900/20 dark:border-green-700/50'
// //                 : securityStatus.overall === 'warning'
// //                   ? 'border-yellow-300/50 bg-gradient-to-br from-yellow-50/80 to-amber-50/80 dark:from-yellow-900/20 dark:to-amber-900/20 dark:border-yellow-700/50'
// //                   : 'border-red-300/50 bg-gradient-to-br from-red-50/80 to-rose-50/80 dark:from-red-900/20 dark:to-rose-900/20 dark:border-red-700/50'
// //             } backdrop-blur-lg`}
// //             role="region"
// //             aria-labelledby="overall-status-heading"
// //             aria-live="polite"
// //           >
// //             <div className="flex items-center justify-between mb-6">
// //               <div className="flex items-center space-x-3">
// //                 <div
// //                   className={`p-3 rounded-full ${
// //                     securityStatus.overall === 'secure'
// //                       ? 'bg-green-100/80 dark:bg-green-900/40'
// //                       : securityStatus.overall === 'warning'
// //                         ? 'bg-yellow-100/80 dark:bg-yellow-900/40'
// //                         : 'bg-red-100/80 dark:bg-red-900/40'
// //                   } backdrop-blur-sm`}
// //                 >
// //                   {getStatusIcon(securityStatus.overall)}
// //                 </div>
// //                 <div>
// //                   <h2
// //                     id="overall-status-heading"
// //                     className="text-2xl font-semibold text-gray-900 dark:text-white"
// //                   >
// //                     System Status:{' '}
// //                     <span className="capitalize time-display">
// //                       {securityStatus.overall}
// //                     </span>
// //                   </h2>
// //                   <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">
// //                     Last updated:{' '}
// //                     {securityStatus.metrics.lastUpdate.toLocaleTimeString()}
// //                   </p>
// //                 </div>
// //               </div>
// //             </div>
// //
// //             <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
// //               <div className="glass-card text-center p-4 bg-white/50 dark:bg-dark-800/50 backdrop-blur-sm hover:bg-white/70 dark:hover:bg-dark-700/50 transition-all">
// //                 <div className="text-3xl font-bold text-primary-600 dark:text-primary-400 time-display">
// //                   {securityStatus.metrics.totalThreats}
// //                 </div>
// //                 <div className="text-sm text-gray-600 dark:text-gray-300 mt-1">
// //                   Total Threats
// //                 </div>
// //               </div>
// //               <div className="glass-card text-center p-4 bg-white/50 dark:bg-dark-800/50 backdrop-blur-sm hover:bg-white/70 dark:hover:bg-dark-700/50 transition-all">
// //                 <div className="text-3xl font-bold text-orange-600 dark:text-orange-400 time-display">
// //                   {securityStatus.metrics.activeAlerts}
// //                 </div>
// //                 <div className="text-sm text-gray-600 dark:text-gray-300 mt-1">
// //                   Active Alerts
// //                 </div>
// //               </div>
// //               <div className="glass-card text-center p-4 bg-white/50 dark:bg-dark-800/50 backdrop-blur-sm hover:bg-white/70 dark:hover:bg-dark-700/50 transition-all">
// //                 <div className="text-3xl font-bold text-green-600 dark:text-green-400 time-display">
// //                   {securityStatus.metrics.backupHealth}%
// //                 </div>
// //                 <div className="text-sm text-gray-600 dark:text-gray-300 mt-1">
// //                   Backup Health
// //                 </div>
// //               </div>
// //               <div className="glass-card text-center p-4 bg-white/50 dark:bg-dark-800/50 backdrop-blur-sm hover:bg-white/70 dark:hover:bg-dark-700/50 transition-all">
// //                 <div className="text-3xl font-bold text-purple-600 dark:text-purple-400 time-display">
// //                   {securityStatus.metrics.integrityScore}%
// //                 </div>
// //                 <div className="text-sm text-gray-600 dark:text-gray-300 mt-1">
// //                   Integrity Score
// //                 </div>
// //               </div>
// //             </div>
// //
// //             {securityStatus.recommendations.length > 0 && (
// //               <div className="glass-card bg-white/30 dark:bg-dark-800/30 p-4 backdrop-blur-sm">
// //                 <h3 className="font-semibold mb-3 flex items-center gap-2 text-gray-900 dark:text-white">
// //                   <ShieldCheck
// //                     className="w-5 h-5 text-primary-500"
// //                     aria-hidden="true"
// //                   />
// //                   Security Recommendations
// //                 </h3>
// //                 <ul className="space-y-2" role="list">
// //                   {securityStatus.recommendations.map((rec, index
// // ) => (
// //                     <li
// //                       key={index}
// //                       className="text-sm text-gray-700 dark:text-gray-300 flex items-start gap-2"
// //                       role="listitem"
// //                     >
// //                       <span className="text-primary-500 mt-0.5">•</span>
// //                       <span>{rec}</span>
// //                     </li>
// //                   ))}
// //                 </ul>
// //               </div>
// //             )}
// //           </section>
// //         )}
// //
// //         {/* Tab Navigation */}
// //         <section
// //           className="alarm-card p-1 bg-gray-100/80 dark:bg-dark-800/80 backdrop-blur-sm"
// //           role="tablist"
// //           aria-label="Security dashboard sections"
// //         >
// //           <div className="flex space-x-1">
// //             {[
// //               {
// //                 key: 'overview',
// //                 label: 'Overview',
// //                 icon: Activity,
// //                 desc: 'View component status overview',
// //               },
// //               {
// //                 key: 'alerts',
// //                 label: 'Alerts',
// //                 icon: Alert,
// //                 desc: 'Manage active security alerts',
// //               },
// //               {
// //                 key: 'diagnostics',
// //                 label: 'Diagnostics',
// //                 icon: Zap,
// //                 desc: 'Run security system tests',
// //               },
// //               {
// //                 key: 'backup',
// //                 label: 'Backup',
// //                 icon: Archive,
// //                 desc: 'Monitor backup systems',
// //               },
// //             ].map(({ key, label, icon: Icon, desc }
// // ) => (
// //               <button
// //                 key={key}
// //                 onClick={(
// // ) => setSelectedTab(key as any)}
// //                 role="tab"
// //                 aria-selected={selectedTab === key}
// //                 aria-controls={`${key}-panel`}
// //                 aria-describedby={`${key}-desc`}
// //                 className={`alarm-button flex items-center space-x-2 px-4 py-3 rounded-lg font-medium transition-all ripple ${
// //                   selectedTab === key
// //                     ? 'alarm-button-primary bg-gradient-to-r from-primary-500 to-primary-600 text-white shadow-lg transform scale-[1.02]'
// //                     : 'text-gray-600 dark:text-gray-300 hover:text-primary-600 dark:hover:text-primary-400 hover:bg-white/50 dark:hover:bg-dark-700/50'
// //                 } backdrop-blur-sm`}
// //               >
// //                 <Icon className="w-4 h-4" aria-hidden="true" />
// //                 <span>{label}</span>
// //                 <span id={`${key}-desc`} className="sr-only">
// //                   {desc}
// //                 </span>
// //               </button>
// //             ))}
// //           </div>
// //         </section>
// //
// //         {/* Tab Content */}
// //         {selectedTab === 'overview' && securityStatus && (
// //           <section
// //             id="overview-panel"
// //             role="tabpanel"
// //             aria-labelledby="overview-tab"
// //             className="space-y-6"
// //           >
// //             <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
// //               Security Components Status
// //             </h3>
// //             <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
// //               {Object.entries(securityStatus.components).map(([component, status]
// // ) => {
// //                 const componentName = component.replace(/([A-Z])/g, ' $1').trim();
// //                 const isHealthy = ['active', 'healthy', 'monitoring'].includes(status);
// //                 const isWarning = ['degraded'].includes(status);
// //
// //                 return (
// //                   <div
// //                     key={component}
// //                     className={`alarm-card glass-card p-6 border backdrop-blur-lg transition-all hover:transform hover:scale-105 ${
// //                       isHealthy
// //                         ? 'border-green-200/50 bg-gradient-to-br from-green-50/50 to-emerald-50/50 dark:from-green-900/10 dark:to-emerald-900/10 dark:border-green-700/30'
// //                         : isWarning
// //                           ? 'border-yellow-200/50 bg-gradient-to-br from-yellow-50/50 to-amber-50/50 dark:from-yellow-900/10 dark:to-amber-900/10 dark:border-yellow-700/30'
// //                           : 'border-red-200/50 bg-gradient-to-br from-red-50/50 to-rose-50/50 dark:from-red-900/10 dark:to-rose-900/10 dark:border-red-700/30'
// //                     }`}
// //                     role="status"
// //                     aria-label={`${componentName} status: ${status}`}
// //                   >
// //                     <div className="flex items-center justify-between mb-4">
// //                       <div className="flex items-center space-x-3">
// //                         <div
// //                           className={`p-2 rounded-full ${
// //                             isHealthy
// //                               ? 'bg-green-100/80 dark:bg-green-900/40'
// //                               : isWarning
// //                                 ? 'bg-yellow-100/80 dark:bg-yellow-900/40'
// //                                 : 'bg-red-100/80 dark:bg-red-900/40'
// //                           } backdrop-blur-sm`}
// //                         >
// //                           {component === 'storage' && (
// //                             <Lock
// //                               className="w-5 h-5 text-gray-700 dark:text-gray-300"
// //                               aria-hidden="true"
// //                             />
// //                           )}
// //                           {component === 'integrity' && (
// //                             <Eye
// //                               className="w-5 h-5 text-gray-700 dark:text-gray-300"
// //                               aria-hidden="true"
// //                             />
// //                           )}
// //                           {component === 'backup' && (
// //                             <Archive
// //                               className="w-5 h-5 text-gray-700 dark:text-gray-300"
// //                               aria-hidden="true"
// //                             />
// //                           )}
// //                           {component === 'monitoring' && (
// //                             <Activity
// //                               className="w-5 h-5 text-gray-700 dark:text-gray-300"
// //                               aria-hidden="true"
// //                             />
// //                           )}
// //                           {!['storage', 'integrity', 'backup', 'monitoring'].includes(
// //                             component
// //                           ) && (
// //                             <Shield
// //                               className="w-5 h-5 text-gray-700 dark:text-gray-300"
// //                               aria-hidden="true"
// //                             />
// //                           )}
// //                         </div>
// //                         <div>
// //                           <h4 className="font-semibold capitalize text-gray-900 dark:text-white text-sm">
// //                             {componentName}
// //                           </h4>
// //                         </div>
// //                       </div>
// //                       <div className="flex items-center">{getStatusIcon(status)}</div>
// //                     </div>
// //                     <div
// //                       className={`px-4 py-2 rounded-full text-sm font-medium inline-flex items-center justify-center w-full ${getStatusColor(status)} backdrop-blur-sm`}
// //                     >
// //                       <span className="capitalize">{status}</span>
// //                     </div>
// //                   </div>
// //                 );
// //               })}
// //             </div>
// //           </section>
// //         )}
// //
// //         {selectedTab === 'alerts' && (
// //           <section
// //             id="alerts-panel"
// //             role="tabpanel"
// //             aria-labelledby="alerts-tab"
// //             className="space-y-6"
// //           >
// //             <div className="flex items-center justify-between">
// //               <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
// //                 Active Security Alerts
// //               </h3>
// //               <div className="glass-card px-3 py-2 bg-white/50 dark:bg-dark-800/50 backdrop-blur-sm rounded-lg">
// //                 <span className="text-sm text-gray-600 dark:text-gray-300">
// //                   {activeAlerts.length} active alert
// //                   {activeAlerts.length !== 1 ? 's' : ''}
// //                 </span>
// //               </div>
// //             </div>
// //
// //             {activeAlerts.length === 0 ? (
// //               <div className="alarm-card text-center py-12">
// //                 <div className="p-4 rounded-full bg-green-100/80 dark:bg-green-900/40 w-fit mx-auto mb-4 backdrop-blur-sm">
// //                   <CheckCircle
// //                     className="w-16 h-16 text-green-600 dark:text-green-400"
// //                     aria-hidden="true"
// //                   />
// //                 </div>
// //                 <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
// //                   All Clear!
// //                 </h4>
// //                 <p className="text-gray-600 dark:text-gray-400">
// //                   No active security alerts detected
// //                 </p>
// //               </div>
// //             ) : (
// //               <div className="space-y-4">
// //                 {activeAlerts
// //       .map((alert: any
// // ) => (
// //                   <div
// //                     key={alert.id}
// //                     className="alarm-card glass-card backdrop-blur-lg border hover:transform hover:scale-[1.02] transition-all"
// //                     role="alert"
// //                     aria-describedby={`alert-${alert.id}-desc`}
// //                   >
// //                     <div className="flex items-start justify-between">
// //                       <div className="flex-1">
// //                         <div className="flex items-center space-x-3 mb-3">
// //                           <span
// //                             className={`px-3 py-1 rounded-full text-xs font-medium backdrop-blur-sm ${getSeverityColor(alert.severity)}`}
// //                           >
// //                             {alert.severity.toUpperCase()}
// //                           </span>
// //                           <span className="text-sm text-gray-600 dark:text-gray-400">
// //                             {alert.timestamp.toLocaleString()}
// //                           </span>
// //                           {alert.acknowledged && (
// //                             <span className="text-xs bg-blue-100/80 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 px-2 py-1 rounded-full border border-blue-200/50 dark:border-blue-700/30">
// //                               Acknowledged
// //                             </span>
// //                           )}
// //                         </div>
// //                         <h4 className="font-semibold mb-2 text-gray-900 dark:text-white">
// //                           {alert.title}
// //                         </h4>
// //                         <p
// //                           id={`alert-${alert.id}-desc`}
// //                           className="text-sm text-gray-700 dark:text-gray-300 mb-4"
// //                         >
// //                           {alert.description}
// //                         </p>
// //                       </div>
// //                       <div className="flex flex-col space-y-2 ml-4">
// //                         {!alert.acknowledged && (
// //                           <button
// //                             onClick={(
// // ) => acknowledgeAlert(alert.id)}
// //                             className="alarm-button px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white text-sm rounded-lg transition-all backdrop-blur-sm ripple"
// //                             aria-label={`Acknowledge alert: ${alert.title}`}
// //                           >
// //                             Acknowledge
// //                           </button>
// //                         )}
// //                         {!alert.resolved && (
// //                           <button
// //                             onClick={(
// // ) => resolveAlert(alert.id)}
// //                             className="alarm-button px-4 py-2 bg-green-600 hover:bg-green-700 text-white text-sm rounded-lg transition-all backdrop-blur-sm ripple"
// //                             aria-label={`Resolve alert: ${alert.title}`}
// //                           >
// //                             Resolve
// //                           </button>
// //                         )}
// //                       </div>
// //                     </div>
// //                   </div>
// //                 ))}
// //               </div>
// //             )}
// //           </section>
// //         )}
// //
// //         {selectedTab === 'diagnostics' && (
// //           <section
// //             id="diagnostics-panel"
// //             role="tabpanel"
// //             aria-labelledby="diagnostics-tab"
// //             className="space-y-6"
// //           >
// //             <div className="flex items-center justify-between">
// //               <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
// //                 Security Diagnostics
// //               </h3>
// //               <button
// //                 onClick={runDiagnostics}
// //                 disabled={loading}
// //                 className="alarm-button alarm-button-primary flex items-center space-x-2 px-6 py-3 bg-gradient-to-r from-purple-500 to-purple-600 hover:from-purple-600 hover:to-purple-700 text-white rounded-lg disabled:opacity-50 disabled:cursor-not-allowed backdrop-blur-sm transition-all ripple"
// //                 aria-label="Run comprehensive security diagnostics"
// //               >
// //                 <Zap
// //                   className={`w-5 h-5 ${loading ? 'animate-pulse' : ''}`}
// //                   aria-hidden="true"
// //                 />
// //                 <span>Run Diagnostics</span>
// //               </button>
// //             </div>
// //
// //             {diagnosticsResults ? (
// //               <div className="alarm-card glass-card backdrop-blur-lg border">
// //                 <div className="flex items-center space-x-4 mb-6">
// //                   <div
// //                     className={`p-3 rounded-full ${
// //                       diagnosticsResults.overall === 'healthy'
// //                         ? 'bg-green-100/80 dark:bg-green-900/40'
// //                         : diagnosticsResults.overall === 'warning'
// //                           ? 'bg-yellow-100/80 dark:bg-yellow-900/40'
// //                           : 'bg-red-100/80 dark:bg-red-900/40'
// //                     } backdrop-blur-sm`}
// //                   >
// //                     {getStatusIcon(diagnosticsResults.overall)}
// //                   </div>
// //                   <div>
// //                     <h4 className="text-2xl font-semibold capitalize text-gray-900 dark:text-white">
// //                       Overall Status:{' '}
// //                       <span className="time-display">{diagnosticsResults.overall}</span>
// //                     </h4>
// //                     <p className="text-gray-600 dark:text-gray-300 mt-1">
// //                       {diagnosticsResults.summary}
// //                     </p>
// //                   </div>
// //                 </div>
// //
// //                 <div className="space-y-4">
// //                   <h5 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
// //                     Diagnostic Tests
// //                   </h5>
// //                   {diagnosticsResults.tests.map((test: any, index: number
// // ) => {
// //                     const isHealthy = ['passed', 'healthy', 'active'].includes(
// //                       test.status
// //                     );
// //                     const isWarning = ['warning', 'degraded'].includes(test.status);
// //
// //                     return (
// //                       <div
// //                         key={index}
// //                         className={`glass-card flex items-start space-x-4 p-4 backdrop-blur-sm border ${
// //                           isHealthy
// //                             ? 'border-green-200/50 bg-green-50/50 dark:bg-green-900/10 dark:border-green-700/30'
// //                             : isWarning
// //                               ? 'border-yellow-200/50 bg-yellow-50/50 dark:bg-yellow-900/10 dark:border-yellow-700/30'
// //                               : 'border-red-200/50 bg-red-50/50 dark:bg-red-900/10 dark:border-red-700/30'
// //                         } rounded-lg transition-all hover:transform hover:scale-[1.02]`}
// //                         role="status"
// //                         aria-label={`${test.name}: ${test.status}`}
// //                       >
// //                         <div
// //                           className={`p-2 rounded-full ${
// //                             isHealthy
// //                               ? 'bg-green-100/80 dark:bg-green-900/40'
// //                               : isWarning
// //                                 ? 'bg-yellow-100/80 dark:bg-yellow-900/40'
// //                                 : 'bg-red-100/80 dark:bg-red-900/40'
// //                           } backdrop-blur-sm flex-shrink-0`}
// //                         >
// //                           {getStatusIcon(test.status)}
// //                         </div>
// //                         <div className="flex-1 min-w-0">
// //                           <h6 className="font-medium text-gray-900 dark:text-white">
// //                             {test.name}
// //                           </h6>
// //                           <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">
// //                             {test.message}
// //                           </p>
// //                           {test.recommendations && test.recommendations.length > 0 && (
// //                             <div className="mt-3">
// //                               <h6 className="text-xs font-medium text-gray-700 dark:text-gray-300 mb-1 block">
// //                                 Recommendations:
// //                               </h6>
// //                               <ul className="space-y-1" role="list">
// //                                 {test.recommendations.map(
// //                                   (rec: string, recIndex: number
// // ) => (
// //                                     <li
// //                                       key={recIndex}
// //                                       className="text-xs text-gray-600 dark:text-gray-400 flex items-start gap-2"
// //                                       role="listitem"
// //                                     >
// //                                       <span className="text-primary-500 mt-0.5 flex-shrink-0">
// //                                         •
// //                                       </span>
// //                                       <span>{rec}</span>
// //                                     </li>
// //                                   )
// //                                 )}
// //                               </ul>
// //                             </div>
// //                           )}
// //                         </div>
// //                       </div>
// //                     );
// //                   })}
// //                 </div>
// //               </div>
// //             ) : (
// //               <div className="alarm-card text-center py-12">
// //                 <div className="p-4 rounded-full bg-purple-100/80 dark:bg-purple-900/40 w-fit mx-auto mb-4 backdrop-blur-sm">
// //                   <Zap
// //                     className="w-16 h-16 text-purple-600 dark:text-purple-400"
// //                     aria-hidden="true"
// //                   />
// //                 </div>
// //                 <h4 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
// //                   Ready to Run Diagnostics
// //                 </h4>
// //                 <p className="text-gray-600 dark:text-gray-400">
// //                   Click "Run Diagnostics" to perform a comprehensive security system
// //                   check
// //                 </p>
// //               </div>
// //             )}
// //           </section>
// //         )}
// //
// //         {selectedTab === 'backup' && (
// //           <section
// //             id="backup-panel"
// //             role="tabpanel"
// //             aria-labelledby="backup-tab"
// //             className="space-y-6"
// //           >
// //             <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
// //               Backup & Recovery Status
// //             </h3>
// //             <div className="alarm-card glass-card backdrop-blur-lg border">
// //               <div className="text-center py-12">
// //                 <div className="p-4 rounded-full bg-primary-100/80 dark:bg-primary-900/40 w-fit mx-auto mb-6 backdrop-blur-sm">
// //                   <Archive
// //                     className="w-16 h-16 text-primary-600 dark:text-primary-400"
// //                     aria-hidden="true"
// //                   />
// //                 </div>
// //                 <h4 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
// //                   Backup System Integration
// //                 </h4>
// //                 <p className="text-gray-600 dark:text-gray-400 mb-2">
// //                   Backup status monitoring will be available here
// //                 </p>
// //                 <p className="text-sm text-gray-500 dark:text-gray-500">
// //                   Advanced backup service integration is currently in development
// //                 </p>
// //
// //                 <div className="mt-8 glass-card bg-white/50 dark:bg-dark-800/50 p-4 backdrop-blur-sm rounded-lg">
// //                   <h5 className="font-semibold text-gray-900 dark:text-white mb-2">
// //                     Coming Soon:
// //                   </h5>
// //                   <ul
// //                     className="text-sm text-gray-600 dark:text-gray-400 space-y-1"
// //                     role="list"
// //                   >
// //                     <li className="flex items-center gap-2" role="listitem">
// //                       <span className="text-primary-500">✓</span>
// //                       Real-time backup health monitoring
// //                     </li>
// //                     <li className="flex items-center gap-2" role="listitem">
// //                       <span className="text-primary-500">✓</span>
// //                       Automated backup verification
// //                     </li>
// //                     <li className="flex items-center gap-2" role="listitem">
// //                       <span className="text-primary-500">✓</span>
// //                       Recovery point management
// //                     </li>
// //                     <li className="flex items-center gap-2" role="listitem">
// //                       <span className="text-primary-500">✓</span>
// //                       Backup performance analytics
// //                     </li>
// //                   </ul>
// //                 </div>
// //               </div>
// //             </div>
// //           </section>
// //         )}
// //       </div>
// //     </main>
// //   );
// // };
//
// export default ComprehensiveSecurityDashboard;
