name: Accessibility Testing (npm)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-a11y:
    name: Unit Accessibility Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run unit accessibility tests (jest-axe)
        run: npm run test:a11y:unit
        env:
          NODE_ENV: test

  e2e-a11y:
    name: E2E Accessibility Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build application
        run: npm run build

      - name: Start preview server
        run: npm run preview &
        env:
          VITE_APP_VERSION: a11y-${{ github.run_id }}

      - name: Run Playwright accessibility checks
        run: npm run test:a11y:e2e
        env:
          NODE_ENV: test

  lighthouse-a11y:
    name: Lighthouse Accessibility Audits
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build application
        run: npm run build

      - name: Start preview server
        run: npm run preview &
        env:
          VITE_APP_VERSION: a11y-${{ github.run_id }}

      - name: Run Lighthouse CI
        run: npm run test:a11y:lighthouse
        env:
          CI: true

  pa11y-a11y:
    name: Pa11y Accessibility Audits
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build application
        run: npm run build

      - name: Start preview server
        run: npm run preview &
        env:
          VITE_APP_VERSION: a11y-${{ github.run_id }}

      - name: Run pa11y-ci audits
        run: npm run test:a11y:pa11y

  summary:
    name: Accessibility Summary
    runs-on: ubuntu-latest
    needs: [unit-a11y, e2e-a11y, lighthouse-a11y, pa11y-a11y]
    if: always()
    steps:
      - name: Create summary
        run: |
          echo "## Accessibility Testing Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Unit: ${{ needs.unit-a11y.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- E2E: ${{ needs.e2e-a11y.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Lighthouse: ${{ needs.lighthouse-a11y.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Pa11y: ${{ needs.pa11y-a11y.result }}" >> $GITHUB_STEP_SUMMARY
