name: Automated Maintenance

on:
  schedule:
    # Daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      run_security:
        description: "Run security updates"
        required: false
        default: "true"
      run_eslint:
        description: "Run ESLint fixes"
        required: false
        default: "true"
      run_types:
        description: "Run type improvements"
        required: false
        default: "false"
      create_pr:
        description: "Create PR with changes"
        required: false
        default: "false"

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Create npm lock file for cache compatibility
        run: |
          # Create package-lock.json if it doesn't exist for npm cache compatibility
          if [ ! -f package-lock.json ] && [ -f bun.lock ]; then
            echo "Creating package-lock.json for npm cache compatibility..."
            npm install --package-lock-only --ignore-scripts --legacy-peer-deps
          fi
          # Also handle dashboard if applicable
          if [ ! -f relife-campaign-dashboard/package-lock.json ] && [ -f relife-campaign-dashboard/bun.lock ]; then
            cd relife-campaign-dashboard
            npm install --package-lock-only --ignore-scripts --legacy-peer-deps
            cd ..
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Security Updates
        if: github.event.inputs.run_security == 'true' || github.event_name == 'schedule'
        run: node scripts/auto-security-updater.js

      - name: Run ESLint Fixes
        if: github.event.inputs.run_eslint == 'true' || github.event_name == 'schedule'
        run: node scripts/auto-eslint-fixer.js

      - name: Run Type Improvements
        if: github.event.inputs.run_types == 'true'
        run: node scripts/auto-type-improver.js

      - name: Create PR with changes
        if: github.event.inputs.create_pr == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            timestamp=$(date +%Y%m%d-%H%M%S)
            branch="auto/maintenance-$timestamp"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b $branch
            git add .
            git commit -m "chore: automated maintenance updates"
            git push origin $branch
            gh pr create --title "🤖 Automated Maintenance Updates" --body "Automated fixes and improvements"
          fi