name: Mobile Testing CI

on:
  push:
    branches: [ main, develop, test/mobile-** ]
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'android/**' 
      - 'ios/**'
      - 'capacitor.config.ts'
      - 'package.json'
      - '.github/workflows/mobile-testing.yml'

env:
  NODE_VERSION: '18'
  JAVA_VERSION: '17'
  API_LEVEL: 30
  TARGET: default
  ARCH: x86_64

jobs:
  mobile-mock-tests:
    name: Mobile Plugin Mock Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run mobile mock tests
        run: npm run test:mobile:mock
        env:
          USE_REAL_DEVICE: false
          CI: true
          
      - name: Generate mobile test coverage
        run: npm run test:mobile:coverage
        env:
          USE_REAL_DEVICE: false
          CI: true
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: mobile-mocks
          name: mobile-mock-tests
          fail_ci_if_error: false

  android-emulator-tests:
    name: Android Emulator Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build web app
        run: npm run build
        
      - name: Sync Capacitor
        run: npx cap sync android
        
      - name: Build Android APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
      - name: Verify APK exists
        run: |
          ls -la android/app/build/outputs/apk/debug/
          test -f android/app/build/outputs/apk/debug/app-debug.apk
          
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.API_LEVEL }}
          
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: ${{ env.TARGET }}
          arch: ${{ env.ARCH }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
          
      - name: Run Android emulator tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: ${{ env.TARGET }}
          arch: ${{ env.ARCH }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            # Install the APK
            adb install android/app/build/outputs/apk/debug/app-debug.apk
            
            # Wait for device to be ready
            adb wait-for-device
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
            
            # Launch the app and run smoke tests
            adb shell am start -n io.ionic.starter/.MainActivity
            sleep 5
            
            # Take screenshot of app launch
            adb exec-out screencap -p > screenshots/app-launch.png
            
            # Run device-specific tests
            USE_REAL_DEVICE=true npm run test:mobile:device || true
            
            # Capture device logs
            adb logcat -d > device-logs/android-logcat.txt
            
            # Get app info
            adb shell dumpsys package io.ionic.starter | grep -A 5 -B 5 "versionName" > device-logs/app-info.txt
            
            # Test Capacitor Device plugin
            adb shell am broadcast -a io.capacitor.plugin.test --es plugin "Device" --es action "getInfo"
            
            echo "Android emulator tests completed"
            
      - name: Create artifact directories
        run: |
          mkdir -p screenshots device-logs
          
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-screenshots
          path: screenshots/
          retention-days: 30
          
      - name: Upload device logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-device-logs
          path: device-logs/
          retention-days: 30
          
      - name: Test results summary
        if: always()
        run: |
          echo "## Android Emulator Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- **API Level**: ${{ env.API_LEVEL }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Architecture**: ${{ env.ARCH }}" >> $GITHUB_STEP_SUMMARY
          echo "- **APK Built**: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- **App Installed**: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- **Screenshots**: 📸 Available in artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- **Device Logs**: 📋 Available in artifacts" >> $GITHUB_STEP_SUMMARY

  ios-simulator-tests:
    name: iOS Simulator Tests (macOS)
    runs-on: macos-latest
    if: ${{ github.event_name == 'push' && contains(github.ref, 'main') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build web app
        run: npm run build
        
      - name: Sync Capacitor
        run: npx cap sync ios
        
      - name: List available simulators
        run: xcrun simctl list devices available
        
      - name: Build iOS app
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
          
      - name: Run iOS simulator tests
        run: |
          # Boot simulator
          xcrun simctl boot "iPhone 15" || true
          sleep 10
          
          # Install and launch app  
          xcrun simctl install booted ios/App/build/Debug-iphonesimulator/App.app
          xcrun simctl launch booted io.ionic.starter
          sleep 5
          
          # Take screenshot
          mkdir -p screenshots
          xcrun simctl io booted screenshot screenshots/ios-app-launch.png
          
          # Run device-specific tests
          USE_REAL_DEVICE=true npm run test:mobile:device || true
          
          echo "iOS simulator tests completed"
          
      - name: Upload iOS screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-screenshots
          path: screenshots/
          retention-days: 30

  test-summary:
    name: Mobile Testing Summary
    runs-on: ubuntu-latest
    needs: [mobile-mock-tests, android-emulator-tests]
    if: always()
    
    steps:
      - name: Generate test summary
        run: |
          echo "# 📱 Mobile Testing Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Test Status" >> $GITHUB_STEP_SUMMARY
          echo "- **Mock Tests**: ${{ needs.mobile-mock-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Android Emulator**: ${{ needs.android-emulator-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Artifacts Available" >> $GITHUB_STEP_SUMMARY
          echo "- 📸 Android Screenshots" >> $GITHUB_STEP_SUMMARY
          echo "- 📋 Android Device Logs" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Test Coverage Reports" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "Check the artifacts for screenshots and device logs to verify Capacitor integration." >> $GITHUB_STEP_SUMMARY